--ALTER TABLE USERSESSIONS DROP CONSTRAINT FK_SELECTEDLINE;
--drop table ORDER_DETAILS;
--drop table ORDERS;
--drop table USERSESSIONS;
--drop table PRODUCTS;

drop table ANNOTATIONS;
drop table PHOTOS;
drop table ASSISTANCES;
drop table DISCHI;
drop table CUSTOMERS;

-- Create the table for customers
CREATE TABLE CUSTOMERS
(
    ID VARCHAR(100) PRIMARY KEY,
    RAGIONE_SOCIALE VARCHAR(255),
    PERSONA_RIFERIMENTO VARCHAR(255),
    EMAIL_RIFERIMENTO VARCHAR(255),
    CELLULARE_RIFERIMENTO VARCHAR(255),
    TELEFONO_AZIENDALE VARCHAR(255),
    EMAIL_AZIENDALE VARCHAR(255),
    PAESE VARCHAR(100),
    CITTA VARCHAR(100),
    NOME_TITOLARE VARCHAR(255),
    CELLULARE_TITOLARE VARCHAR(255),
    EMAIL_TITOLARE VARCHAR(255),
    SITO_WEB VARCHAR(510),
    VOLTE_CONTATTATI INT DEFAULT 0 CHECK (VOLTE_CONTATTATI >= 0),
    ULTIMA_CHIAMATA DATE,
    PROSSIMA_CHIAMATA DATE,
    DATA_ACQUISIZIONE DATE DEFAULT CURRENT_DATE,
    BUSINESS VARCHAR(20),
    OPERATORE_ASSEGNATO VARCHAR(20),
    INFORMATION BOOLEAN DEFAULT FALSE,
    CATALOG BOOLEAN DEFAULT FALSE,
    SAMPLE BOOLEAN DEFAULT FALSE,
    PVU CLOB
);

CREATE TABLE ANNOTATIONS
(
    ID                VARCHAR(100) PRIMARY KEY,
    CUSTOMER_ID       VARCHAR(100) NOT NULL,
    DATA_CHIAMATA     DATE         NOT NULL,
    PROSSIMA_CHIAMATA DATE,
    OPERATORE         VARCHAR(20)  NOT NULL,
    CONTENUTO         CLOB         NOT NULL,
    INFORMATION       BOOLEAN default false,
    CATALOG           BOOLEAN default false,
    SAMPLE            BOOLEAN default false,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID) ON DELETE CASCADE
);

CREATE TABLE DISCHI
(
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    TIPOLOGIA VARCHAR(20),
    MISURA VARCHAR(2),
    COLORE VARCHAR(4),
    DIAMETRO VARCHAR (2),
    LOTTO VARCHAR(6),
    PROBLEMA VARCHAR(50)
);

CREATE TABLE ASSISTANCES
(
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CUSTOMER_ID VARCHAR(100) NOT NULL,
    DISCO_ID INT,
    RIV_NOME VARCHAR (255),
    RIV_RIFERIMENTO VARCHAR (255),
    RIV_TELEFONO VARCHAR (255),
    RIV_EMAIL VARCHAR (255),
    LAB_NOME VARCHAR (255),
    LAB_RIFERIMENTO VARCHAR (255),
    LAB_TELEFONO VARCHAR (255),
    LAB_EMAIL VARCHAR (255),
    DESCRIZIONE CLOB,
    SINTERIZZAZIONE CLOB,
    ANALISI BLOB,
    DATA DATE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (DISCO_ID) REFERENCES DISCHI (ID)
);

CREATE TABLE PHOTOS
(
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ASSISTANCE_ID INT NOT NULL,
    DISCO_ID INT NOT NULL,
    NOME VARCHAR(255),
    IMMAGINE BLOB,
    FOREIGN KEY (ASSISTANCE_ID) REFERENCES ASSISTANCES (ID),
    FOREIGN KEY (DISCO_ID) REFERENCES DISCHI (ID)
);