--ALTER TABLE USERSESSIONS DROP CONSTRAINT FK_SELECTEDLINE;
--drop table ORDER_DETAILS;
--drop table ORDERS;
--drop table USERSESSIONS;
--drop table PRODUCTS;

drop table ANNOTATIONS;
drop table CUSTOMERS;

-- Create the table for customers
CREATE TABLE CUSTOMERS
(
    ID VARCHAR(100) PRIMARY KEY,
    RAGIONE_SOCIALE VARCHAR(255),
    PERSONA_RIFERIMENTO VARCHAR(255),
    EMAIL_RIFERIMENTO VARCHAR(255),
    CELLULARE_RIFERIMENTO VARCHAR(255),
    TELEFONO_AZIENDALE VARCHAR(255),
    EMAIL_AZIENDALE VARCHAR(255),
    PAESE VARCHAR(100),
    CITTA VARCHAR(100),
    NOME_TITOLARE VARCHAR(255),
    CELLULARE_TITOLARE VARCHAR(255),
    EMAIL_TITOLARE VARCHAR(255),
    SITO_WEB VARCHAR(510),
    VOLTE_CONTATTATI INT DEFAULT 0 CHECK (VOLTE_CONTATTATI >= 0),
    ULTIMA_CHIAMATA DATE,
    PROSSIMA_CHIAMATA DATE,
    DATA_ACQUISIZIONE DATE DEFAULT CURRENT_DATE,
    BUSINESS VARCHAR(20),
    OPERATORE_ASSEGNATO VARCHAR(20),
    INFORMATION BOOLEAN DEFAULT FALSE,
    CATALOG BOOLEAN DEFAULT FALSE,
    SAMPLE BOOLEAN DEFAULT FALSE,
    PVU CLOB
);

CREATE TABLE ANNOTATIONS
(
    ID                VARCHAR(100) PRIMARY KEY,
    CUSTOMER_ID       VARCHAR(100) NOT NULL,
    DATA_CHIAMATA     DATE         NOT NULL,
    PROSSIMA_CHIAMATA DATE,
    OPERATORE         VARCHAR(20)  NOT NULL,
    CONTENUTO         CLOB         NOT NULL,
    INFORMATION       BOOLEAN default false,
    CATALOG           BOOLEAN default false,
    SAMPLE            BOOLEAN default false,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID) ON DELETE CASCADE
);

CREATE TABLE DISCHI (
    ID INT PRIMARY GENERATED ALWAYS AS IDENTITY,
    TIPOLOGIA VARCHAR(20),
    MISURA VARCHAR(2),
    COLORE VARCHAR(4),
    DIAMETRO VARCHAR (2),
    LOTTO VARCHAR(6),
    PROBLEMA VARCHAR(50)
);

CREATE TABLE ASSISTANCES (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CUSTOMER_ID VARCHAR(100) NOT NULL,
    DISCO_ID INT,
    RIV_NOME VARCHAR (255),
    RIV_RIFERIMENTO VARCHAR (255),
    RIV_TELEFONO VARCHAR (255),
    RIV_EMAIL VARCHAR (255),
    LAB_NOME VARCHAR (255),
    LAB_RIFERIMENTO VARCHAR (255),
    LAB_TELEFONO VARCHAR (255),
    LAB_EMAIL VARCHAR (255),
    DESCRIZIONE CLOB,
    SINTERIZZAZIONE CLOB,
    ANALISI CLOB,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (DISCO_ID) REFERENCES DISCHI (ID) ON DELETE CASCADE
);

CREATE TABLE PHOTOS (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ASSISTANCE_ID INT NOT NULL,
    DISCO_ID INT NOT NULL,
    NOME VARCHAR(255),
    IMMAGINE BLOB,
    FOREIGN KEY (ASSISTANCE_ID) REFERENCES ASSISTANCES (ID),
    FOREIGN KEY (DISCO_ID) REFERENCES DISCHI (ID) ON DELETE CASCADE
);

INSERT INTO CUSTOMERS (ID, RAGIONE_SOCIALE, PERSONA_RIFERIMENTO, EMAIL_RIFERIMENTO, CELLULARE_RIFERIMENTO, TELEFONO_AZIENDALE, EMAIL_AZIENDALE, PAESE, CITTA, NOME_TITOLARE, CELLULARE_TITOLARE, EMAIL_TITOLARE, SITO_WEB, VOLTE_CONTATTATI, ULTIMA_CHIAMATA, PROSSIMA_CHIAMATA, DATA_ACQUISIZIONE, BUSINESS, OPERATORE_ASSEGNATO, INFORMATION, CATALOG, SAMPLE)
VALUES
    ('1b7d61b5-391c-4a3d-a8a7-eb46a7a46a16', 'Tech Labs Inc.', 'Giulia Ferrari', 'giulia.ferrari@techlabs.com', '3201234567', '061234567', 'contact@techlabs.com', 'Italy', 'Rome', 'Luca Bianchi', '3297654321', 'luca.bianchi@techlabs.com', 'www.techlabs.com', 5, '2025-02-15', '2025-03-01', '2024-12-01', 'RIVENDITORE', 'VICTORIA', TRUE, TRUE, FALSE),

    ('ccc4e047-772e-4c29-a7af-145837df654b', 'Global Resellers', 'Marco De Luca', 'marco.deluca@globalresellers.com', '3312345678', '0412345678', 'sales@globalresellers.com', 'Italy', 'Milan', 'Antonio Verdi', '3387654321', 'antonio.verdi@globalresellers.com', 'www.globalresellers.com', 10, '2025-02-18', '2025-03-05', '2024-11-10', 'LABORATORIO', 'TERESA', TRUE, TRUE, TRUE),

    ('3dd963f6-0b49-4efa-b5dd-1b988a4dab70', 'XYZ Distribution', 'Elena Russo', 'elena.russo@xyzdistribution.com', '3401234567', '055234567', 'info@xyzdistribution.com', 'USA', 'New York', 'John Smith', '3456789012', 'john.smith@xyzdistribution.com', 'www.xyzdistribution.com', 2, '2025-02-20', '2025-03-10', '2025-01-15', 'DISTRIBUTORE', 'TERESA', FALSE, TRUE, TRUE);

INSERT INTO ANNOTATIONS (ID, CUSTOMER_ID, DATA_CHIAMATA, PROSSIMA_CHIAMATA, OPERATORE, CONTENUTO)
VALUES ('3dd963f6-0b49-4efa-b5de-1b998a4dab70', '3dd963f6-0b49-4efa-b5dd-1b988a4dab70', '2025-02-24', '2025-03-10', 'TERESA', 'Cliente interessato al nuovo catalogo.');