--ALTER TABLE USERSESSIONS DROP CONSTRAINT FK_SELECTEDLINE;
--drop table ORDER_DETAILS;
--drop table ORDERS;
--drop table USERSESSIONS;
--drop table PRODUCTS;

drop table CUSTOMERS;

-- Create the table for customers
CREATE TABLE CUSTOMERS
(
    ID VARCHAR(100) PRIMARY KEY,
    RAGIONE_SOCIALE VARCHAR(100),
    PERSONA_RIFERIMENTO VARCHAR(100),
    EMAIL_RIFERIMENTO VARCHAR(100),
    CELLULARE_RIFERIMENTO VARCHAR(100),
    TELEFONO_AZIENDALE VARCHAR(100),
    EMAIL_AZIENDALE VARCHAR(100),
    PAESE VARCHAR(100),
    CITTA VARCHAR(100),
    NOME_TITOLARE VARCHAR(100),
    CELLULARE_TITOLARE VARCHAR(100),
    EMAIL_TITOLARE VARCHAR(100),
    SITO_WEB VARCHAR(100),
    VOLTE_CONTATTATI INT DEFAULT 0 CHECK (VOLTE_CONTATTATI >= 0),
    ULTIMA_CHIAMATA DATE,
    PROSSIMA_CHIAMATA DATE,
    DATA_ACQUISIZIONE DATE DEFAULT CURRENT_DATE,
    BUSINESS VARCHAR(20),
    OPERATORE_ASSEGNATO VARCHAR(20),
    INFORMATION BOOLEAN DEFAULT FALSE,
    CATALOG BOOLEAN DEFAULT FALSE,
    SAMPLE BOOLEAN DEFAULT FALSE
);

INSERT INTO CUSTOMERS (ID, RAGIONE_SOCIALE, PERSONA_RIFERIMENTO, EMAIL_RIFERIMENTO, CELLULARE_RIFERIMENTO, TELEFONO_AZIENDALE, EMAIL_AZIENDALE, PAESE, CITTA, NOME_TITOLARE, CELLULARE_TITOLARE, EMAIL_TITOLARE, SITO_WEB, VOLTE_CONTATTATI, ULTIMA_CHIAMATA, PROSSIMA_CHIAMATA, DATA_ACQUISIZIONE, BUSINESS, OPERATORE_ASSEGNATO, INFORMATION, CATALOG, SAMPLE)
VALUES
    ('5', 'Tech Labs Inc.', 'Giulia Ferrari', 'giulia.ferrari@techlabs.com', '3201234567', '061234567', 'contact@techlabs.com', 'Italy', 'Rome', 'Luca Bianchi', '3297654321', 'luca.bianchi@techlabs.com', 'www.techlabs.com', 5, '2025-02-15', '2025-03-01', '2024-12-01', 'LABORATORY', 'Marco Rossi', TRUE, TRUE, FALSE),

    ('2', 'Global Resellers', 'Marco De Luca', 'marco.deluca@globalresellers.com', '3312345678', '0412345678', 'sales@globalresellers.com', 'Italy', 'Milan', 'Antonio Verdi', '3387654321', 'antonio.verdi@globalresellers.com', 'www.globalresellers.com', 10, '2025-02-18', '2025-03-05', '2024-11-10', 'RESELLER', 'Francesca Lodi', TRUE, TRUE, TRUE),

    ('3', 'XYZ Distribution', 'Elena Russo', 'elena.russo@xyzdistribution.com', '3401234567', '055234567', 'info@xyzdistribution.com', 'USA', 'New York', 'John Smith', '3456789012', 'john.smith@xyzdistribution.com', 'www.xyzdistribution.com', 2, '2025-02-20', '2025-03-10', '2025-01-15', 'DISTRIBUTOR', 'Giovanni Mancini', FALSE, TRUE, TRUE);